# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020 Carles Fernandez-Prades <carles.fernandez@cttc.es>
name: Code linting

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: brew install llvm && ln -s /usr/local/opt/llvm/bin/clang-format /usr/local/bin
    - name: run clang-format
      run: find . -iname \*.h -o -iname \*.c -o -iname \*.cpp -o -iname \*.hpp | xargs clang-format -style=file -i
    - name: check
      run: git diff > clang_format.patch && echo -e "if \n [ -s clang_format.patch ] \nthen \n echo "clang-format not applied:"; echo ""; more clang_format.patch; exit 1 \nfi \n" > detect && chmod +x ./detect && ./detect


  clang-tidy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: brew install llvm pkg-config hdf5 armadillo lapack gflags glog gnuradio libmatio log4cpp pugixml protobuf && ln -s /usr/local/opt/llvm/bin/clang-tidy /usr/local/bin && ln -s /usr/local/Cellar/llvm/9.*/bin/clang-apply-replacements /usr/local/bin && cp /usr/local/Cellar/llvm/9.*/share/clang/run-clang-tidy.py /usr/local/bin && pip3 install mako && pip3 install six
    - name: Prepare run
      run: cd build && cmake -DENABLE_FPGA=ON .. && make volk_gnsssdr_module gtest-1.10.0 core_monitor pvt_libs gpstk-2.12
    - name: run clang-tidy
      run: cd build && run-clang-tidy.py -fix
    - name: check
      run: git diff > clang_tidy.patch && echo -e "if \n [ -s clang_tidy.patch ] \nthen \n echo "clang_tidy not applied:"; echo ""; more clang_tidy.patch; exit 1 \nfi \n" > detect && chmod +x ./detect && ./detect


  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: reuse lint
